services:
  backend:
    build:
      context: .
      dockerfile: apps/love-travel-back/Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_healthy
      mongo_db:
        condition: service_started
    networks:
      - love-travel-network

  frontend:
    build:
      context: .
      dockerfile: apps/love-travel-front/Dockerfile.frontend
    ports:
      - "8080:81"
    networks:
      - love-travel-network
  # Banco Relacional
  postgres_db:
    image: postgres:15
    container_name: travel_sql
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME-admin} -d ${DB_DATABASE:-love_travel_db}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - love-travel-network

  # Banco Não relacional
  mongo_db:
    image: mongo:latest
    container_name: travel_nosql
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27018:27017"
    networks:
      - love-travel-network

  # Cache
  redis_cache:
    image: redis:alpine
    container_name: travel_cache
    ports:
      - "6379:6379"
    networks:
      - love-travel-network
  # Monitoramento de Logs
  dozzle:
    image: amir20/dozzle:latest
    container_name: travel_monitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8081:8080"
    networks:
      - love-travel-network

# Rede virtual isolada para os serviços se comunicarem internamente com segurança e isolamento entre os containers.
networks:
  love-travel-network:
    driver: bridge

# Volumes para persistência de dados
volumes:
  postgres_data:
