name: Workflow Love Travel

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            apps/love-travel-front/package-lock.json

      - name: Install dependencies (frontend)
        working-directory: apps/love-travel-front
        run: npm install

      - name: Run Lint (frontend)
        working-directory: apps/love-travel-front
        run: npm run lint
        
      - name: Build Project (frontend)
        working-directory: apps/love-travel-front
        run: npm run build

  backend:
    runs-on: ubuntu-latest
    services:
      postgres_db:
        image: postgres:15
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: user_test
          POSTGRES_PASSWORD: password_test
          POSTGRES_DB: database_test
        options: >-
          --health-cmd="pg_isready -U user_test -d database_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            apps/love-travel-back/package-lock.json

      - name: Install dependencies (backend)
        working-directory: apps/love-travel-back

        run: npm install
      - name: Run Lint (backend)
        continue-on-error: true

        working-directory: apps/love-travel-back
        run: npm run lint

      - name: Build Project (backend)
        working-directory: apps/love-travel-back
        run: npm run build

